name: Build SkriptMigrate

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java environement
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          java-package: jdk
          architecture: x64

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build SkriptMigrate
        run: ./gradlew build

      - name: Upload nightly build
        uses: actions/upload-artifact@v4
        with:
          name: SkriptMigrate
          path: app/build/libs/SkriptMigrate.jar
